### ISSUE TITLE
Client: Allow users to select/view sires

### ISSUE THREAD

**Issue by delventhalz** [hyperledger/education-cryptomoji#43]
Users should be able to select one of their cryptomoji as a sire, available for breeding. 

They should be able to view the available sires.

~They should be able to select a sire and one of their own cryptomoji and breed them.~ (Moved to #68.)

**Comment by therobinkim** [comment]
hey @taylorpage, since we're deprioritizing the OFFER related functionality I was supposed to work on, I'd like to split this task into 2 subtasks so that I can help out w/ the breeding aspect! just wanted to reach out first in case you started any work on this that I should get synced up on
