### ISSUE TITLE
my bitcoin wallet need private key when I send bitcoin to any address.

### ISSUE THREAD

**Issue by max5903** [hyperledger/education-cryptomoji#66]
is there any one know about how to find private key when I send bitcoin it shows some message that. "this action requires the private key for the bitcoin address. and when I send bitcoin to anyone so it will return into my wallet after 12-18 hours. please help me.

**Comment by delventhalz** [comment]
Sorry, no bitcoin users here. This is an educational course for Hyperledger Sawtooth, an enterprise blockchain completely distinct from bitcoin. Your private key is a secret known only to the user who controls the funds, so if you were trying to withdraw from someone else's account you would get an error. Or perhaps your private key is just mis-entered or something. Beyond that, I have no ideas. I would recommend looking for a support forum for the bitcoin wallet you are using.

**Comment by zeta009** [comment]
Max how much you offer me to get your privatekey?

**Comment by max5903** [comment]
Hi, tell me how much you want? I can pay you about 100 btc for this work.
But i need to be sure that nobody steal that btc from that address. I know
its someone else bitcoin address but thats my friend.
