### ISSUE TITLE
Readme: Emphasize that working on client and TP in parallel is recommended

### ISSUE THREAD

**Issue by therobinkim** [hyperledger/education-cryptomoji#95]
> For Cryptomoji, the client and processor are each in their own directory, with their own tests, and their own READMEs. There is no particular order they need to be built in, but we recommended you develop them in parallel based on functionality. For example, implement "collection creation" on both the client and the processor before moving on to "sire selection" on either.

from `/code/part-two/README.md`

I wonder if we can highlight this somehow or drop additional reminders into the README for `client` or `processor` in case developers skim through the instructions too quickly.

**Comment by delventhalz** [comment]
Should be addressed as a part of version 2 refactor #121
