### ISSUE TITLE
When testing the Blockchain class, make sure the addBlock method correctly adds previousHash to the added block

### ISSUE THREAD

**Issue by azangru** [hyperledger/education-cryptomoji#96]
The `addBlock` method of the Blockchain class should pass the correct `previousHash` to the newly added block. This is not currently checked in the tests for the Blockchain class. So when I made the following typo:

```js
  addBlock(transactions) {
    const previousHash = this.getHeadBlock().previousHash; // instead of this.getHeadBlock().hash;
    const newBlock = new Block(transactions, previousHash);
    this.blocks.push(newBlock);
  }
```

the tests didn’t catch that (although later tests did).

**Comment by therobinkim** [comment]
Fixed by #112
